### ISSUE TITLE
Shared StoredState between kubernetes workload pods

### ISSUE THREAD

**Issue by davigar15** [canonical/operator#240] opened 2020-04-24 09:26 UTC
Hello,

@dshcherb and I have discovered an unintended behavior in K8s charms using the operator framework. The StoredState is not supposed to be shared between units, but it is. 

Operator pod:
```
|-- unit-mongodb-k8s-0
|   |-- charm -> /var/lib/juju/agents/application-mongodb-k8s/charm

`-- unit-mongodb-k8s-1
    |-- charm -> /var/lib/juju/agents/application-mongodb-k8s/charm
```

The framework creates an sqlite db file in the current working directory which happens to be:
-  `/var/lib/juju/agents/<unit-name>/charm`
which is, in reality,:
- `/var/lib/juju/agents/<application-app-name>`

Thus, the DB is shared between units which is unintended.

Full tree in the operator pod under /var/lib/juju/agents
```
# tree -a
.
|-- application-mongodb-k8s
|   |-- agent.conf
|   |-- charm
|   |   |-- .gitignore
|   |   |-- .gitmodules
|   |   |-- .juju-charm
|   |   |-- .unit-state.db
|   |   |-- README.md
|   |   |-- config.yaml
|   |   |-- hooks
|   |   |   |-- cluster-relation-broken -> ../src/charm.py
|   |   |   |-- cluster-relation-changed -> ../src/charm.py
|   |   |   |-- cluster-relation-departed -> ../src/charm.py
|   |   |   |-- cluster-relation-joined -> ../src/charm.py
|   |   |   |-- collect-metrics -> ../src/charm.py
|   |   |   |-- config-changed -> ../src/charm.py
|   |   |   |-- install -> ../src/charm.py
|   |   |   |-- leader-elected -> ../src/charm.py
|   |   |   |-- leader-settings-changed -> ../src/charm.py
|   |   |   |-- mongodb-relation-broken -> ../src/charm.py
|   |   |   |-- mongodb-relation-changed -> ../src/charm.py
|   |   |   |-- mongodb-relation-departed -> ../src/charm.py
|   |   |   |-- mongodb-relation-joined -> ../src/charm.py
|   |   |   |-- post-series-upgrade -> ../src/charm.py
|   |   |   |-- pre-series-upgrade -> ../src/charm.py
|   |   |   |-- remove -> ../src/charm.py
|   |   |   |-- start -> ../src/charm.py
|   |   |   |-- stop -> ../src/charm.py
|   |   |   |-- update-status -> ../src/charm.py
|   |   |   `-- upgrade-charm -> ../src/charm.py
|   |   |-- lib
|   |   |   `-- ops -> ../mod/operator/ops
|   |   |-- metadata.yaml
|   |   |-- mod
|   |   |   `-- operator
|   |   |       |-- .flake8
|   |   |       |-- .gitignore
|   |   |       |-- .travis.yml
|   |   |       |-- LICENSE.txt
|   |   |       |-- README.md
|   |   |       |-- ops
|   |   |       |   |-- __init__.py
|   |   |       |   |-- __pycache__
|   |   |       |   |   |-- __init__.cpython-36.pyc
|   |   |       |   |   |-- charm.cpython-36.pyc
|   |   |       |   |   |-- framework.cpython-36.pyc
|   |   |       |   |   |-- log.cpython-36.pyc
|   |   |       |   |   |-- main.cpython-36.pyc
|   |   |       |   |   `-- model.cpython-36.pyc
|   |   |       |   |-- charm.py
|   |   |       |   |-- framework.py
|   |   |       |   |-- jujuversion.py
|   |   |       |   |-- log.py
|   |   |       |   |-- main.py
|   |   |       |   |-- model.py
|   |   |       |   `-- testing.py
|   |   |       |-- run_tests
|   |   |       |-- setup.py
|   |   |       `-- test
|   |   |           |-- __init__.py
|   |   |           |-- bin
|   |   |           |   |-- relation-ids
|   |   |           |   `-- relation-list
|   |   |           |-- charms
|   |   |           |   `-- test_main
|   |   |           |       |-- config.yaml
|   |   |           |       |-- lib
|   |   |           |       |   |-- __init__.py
|   |   |           |       |   `-- ops -> ../../../../ops
|   |   |           |       |-- metadata.yaml
|   |   |           |       `-- src
|   |   |           |           `-- charm.py
|   |   |           |-- test_charm.py
|   |   |           |-- test_framework.py
|   |   |           |-- test_helpers.py
|   |   |           |-- test_infra.py
|   |   |           |-- test_jujuversion.py
|   |   |           |-- test_log.py
|   |   |           |-- test_main.py
|   |   |           |-- test_model.py
|   |   |           `-- test_testing.py
|   |   |-- revision
|   |   |-- src
|   |   |   |-- __pycache__
|   |   |   |   `-- mongodb_cluster.cpython-36.pyc
|   |   |   |-- charm.py
|   |   |   `-- mongodb_cluster.py
|   |   `-- version
|   |-- operator.yaml
|   |-- state
|   |   |-- bundles
|   |   |   |-- downloads
|   |   |   `-- local_3a_kubernetes_2f_mongodb-k8s-0
|   |   |-- deployer
|   |   |   `-- manifests
|   |   |       `-- local_3a_kubernetes_2f_mongodb-k8s-0
|   |   `-- operator
|   `-- template-agent.conf
|-- unit-mongodb-k8s-0
|   |-- charm -> /var/lib/juju/agents/application-mongodb-k8s/charm
|   |-- operator-client-cache.yaml
|   |-- run.socket
|   `-- state
|       |-- relations
|       |   `-- 0
|       |       `-- mongodb-k8s-1
|       |-- storage
|       `-- uniter
`-- unit-mongodb-k8s-1
    |-- charm -> /var/lib/juju/agents/application-mongodb-k8s/charm
    |-- operator-client-cache.yaml
    |-- run.socket
    `-- state
        |-- relations
        |   `-- 0
        |       `-- mongodb-k8s-0
        |-- storage
        `-- uniter

35 directories, 83 files
```

**Comment by niemeyer** [comment] 2020-04-24 13:45
Thanks for the report. This is definitely an issue that will need addressing on juju or the framework. We'll catch up with @jameinel when he's back next week.

**Comment by wallyworld** [comment] 2020-05-13 21:50
Each charm does maintain a separate state directory as can be seen from the directory listing. Juju does maintain separate state for each charm. See unit-mongodb-k8s-0/state and unit-mongodb-k8s-1/state in the above dir listing.

In Juju 2.7, there is a single copy of the charm code (not state) shared between each unit. But in 2.8 this has been changed so that each unit does get its own copy. 

So any issues with state being written to somewhere other than the separate state dir for each unit should be fixed in 2.8. Also note in 2.8, state is stored in the controller anyway so there is no local on disk charm state anymore.

**Comment by chipaca** [comment] 2020-05-20 13:31
> Also note in 2.8, state is stored in the controller anyway so there is no local on disk charm state anymore.

not without further to-be-done work in both juju and the operator framework though

**Comment by jameinel** [comment] 2020-06-02 06:32
duplicate of #317

**Closed** 2020-06-11 12:53 UTC
