### ISSUE TITLE
[enhancement proposal] Refactor Harness to reinitialize and discard Charm on every event dispatch.

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#789] opened 2022-06-27 07:29 UTC
I think it might be worth it to refactor the harness to work more like ops-in-production does. 
Namely: not just initialize the charm, do things and fire events on this one instance, but rather: only initialize the charm on every event dispatch, then discard it. 
This would be helpful to catch beginner mistakes such as attempting to store state into the charm object.
Also it will remove the need for workarounds like #758 and allow for easier unittesting of code containing `__init__` logic (without forcing the user to remember to `reinitialize_charm()` for example.

**Comment by rwcarlsen** [comment] 2022-06-27 14:43
This seems like a duplicate of https://github.com/canonical/operator/issues/736.

**Comment by PietroPasotti** [comment] 2022-06-28 08:01
Funny, apparently I am very keen on this but not keen enough to remember I raised the issue already. :/

**Closed** 2022-06-28 08:00 UTC
