### ISSUE TITLE
cannot unconditionally set status in `__init__`

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#792] opened 2022-07-06 09:17 UTC
A charm cannot unconditionally set status in `__init__`
Reason is, if the unit is being torn down, status_set will raise an error:
![image](https://user-images.githubusercontent.com/6230162/177515407-a294078e-73f1-4c42-8597-4a0ea9856201.png)

Interestingly enough, it looks like the last events the charm received did NOT include the teardown sequence:

```
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ timestamp ┃ tcp-requirer-mock/0                ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 10:50:15  │ ingress-per-unit-relation-changed  │
│ 10:50:15  │ ingress-per-unit-relation-joined   │
│ 10:50:10  │ ingress-per-unit-relation-created  │
│ 10:49:59  │ update-status                      │
│ 10:48:41  │ ingress-per-unit-relation-departed │
│ 10:45:55  │ tcp-server-pebble-ready            │
│ 10:45:53  │ ingress-per-unit-relation-changed  │
│ 10:45:52  │ ingress-per-unit-relation-changed  │
│ 10:45:52  │ ingress-per-unit-relation-joined   │
│ 10:45:52  │ ingress-per-unit-relation-created  │
└───────────┴────────────────────────────────────┘
```

I'm not sure if this is related.

Point remains: should we warn against setting status in init, or places where the unit is not guaranteed to exist?
Should we raise a more informative error message? 
Should we simply silently fail if one is trying to set a status on a dying unit? After all, we don't really care. It's just clutter in the debug-log.

**Comment by rwcarlsen** [comment] 2022-07-13 16:02
For this particular case, it might be worth just catching the exception and putting an entry in the debug log.  Especially since charms don't have any way of "knowing" that the status-set will fail in advance.

**Comment by benhoyt** [comment] 2023-05-02 10:11
1) This has been a while, so we should probably try to reproduce this on Juju 3 and see what events we get.
2) Probably the least invasive change would be to have ops catch the ModelError in status-set, and if it includes "unit not found" re-raise a more specific exception subclass that helps the charmer debug: "Juju reported unit not found -- is the unit being torn down?" or similar.

**Comment by benhoyt** [comment] 2023-10-04 03:29
@PietroPasotti What's the actual concern here: noise in the debug log? The unit blipping into error state for a second during teardown? Or something else? To me the current behaviour seems okay, but just making sure I'm not missing something.

**Comment by IronCore864** [comment] 2024-03-19 03:19
I struggle to reproduce it, I need some help here @PietroPasotti 

I tried to set the status in `__init__` then remove a unit. Even tried to add a for loop to set it many times then remove units/kill pods/etc., but still failed to reproduce it...

Simple test charm used:

```python
#!/usr/bin/env python3
import ops


class SampleK8SCharm(ops.CharmBase):
    def __init__(self, *args):
        super().__init__(*args)
        # here also tried in a for loop
        self.unit.status = ops.BlockedStatus("test")
        self.framework.observe(self.on['httpbin'].pebble_ready, self._on_httpbin_pebble_ready)
        # also tried setting status in a handler for `self.on.remove`

    def _on_httpbin_pebble_ready(self, event: ops.PebbleReadyEvent):
        container = event.workload
        container.add_layer("httpbin", self._pebble_layer, combine=True)
        container.replan()
        self.unit.status = ops.ActiveStatus()

    @property
    def _pebble_layer(self) -> ops.pebble.LayerDict:
        return {
            "summary": "httpbin layer",
            "description": "pebble config layer for httpbin",
            "services": {
                "httpbin": {
                    "override": "replace",
                    "summary": "httpbin",
                    "command": "gunicorn -b 0.0.0.0:80 httpbin:app -k gevent",
                    "startup": "enabled",
                    "environment": {
                        "GUNICORN_CMD_ARGS": f"--log-level {self.model.config['log-level']}"
                    },
                }
            },
        }


if __name__ == "__main__":
    ops.main(SampleK8SCharm)
```

**Comment by PietroPasotti** [comment] 2024-03-19 10:55
The charm that this error showed up in originally was https://github.com/canonical/traefik-k8s-operator/blob/main/tests/integration/testers/tcp/src/charm.py

I haven't tried it out since, possibly the issue is gone in latest juju.

As you can see that charm sets active in __init__. I recall it errored out during teardown, but I can't remember precisely at which stage.

**Comment by IronCore864** [comment] 2024-03-20 06:57
> The charm that this error showed up in originally was https://github.com/canonical/traefik-k8s-operator/blob/main/tests/integration/testers/tcp/src/charm.py
> 
> I haven't tried it out since, possibly the issue is gone in latest juju.
> 
> As you can see that charm sets active in **init**. I recall it errored out during teardown, but I can't remember precisely at which stage.

Hi Pietro,

I tried with traefic-k8s chart (latest/stable revision 169) with juju (version 3.1.7-genericlinux-amd64 and 3.4.0-genericlinux-amd64) but could not reproduce. I tried to add unit and remove unit and it seems the state transfer looks fine, ready -> maintenance -> terminated.

Screenshot:

<img width="1402" alt="Screenshot 2024-03-19 at 22 07 19" src="https://github.com/canonical/operator/assets/19277614/25eeccec-f052-41b4-a09c-9c104e53c846">

@benhoyt shall we close this issue for now?

**Comment by benhoyt** [comment] 2024-03-20 20:55
Yeah, let's close this for now -- presuming the issue has gone away in recent version of Juju. If we have a clear repro in future, happy to reopen.

**Closed by benhoyt** 2024-03-20 20:55 UTC
Labels: feature, small item, 24.04
