### ISSUE TITLE
Harness provides no means to test ops.model.Application.planned_units()

### ISSUE THREAD

**Issue by mmanciop** [canonical/operator#636] opened 2021-10-06 15:36 UTC
The test harness provides no means to test what happens when a charm is scaled up or down and its logic relies on `ops.model.Application.planned_units()`. This could be addressed via a `ops.testing.Harness.set_planned_unit(<int>)` handle and, to my understanding, should fire a `config_change` event.

**Comment by jameinel** [comment] 2021-10-06 19:39
So we do have some support for things like adding units to a peer relation.
However, the semantic of adding a unit to a relation is that it
immediately enters scope (and you get 'relation-joined'). The *point* of
planned_units is to account for the number of units that exist in the Juju
model but have *not* yet finished provisioning. (so that 'rabbit-mq' knows
once there is an expected quorum)
As such, when testing you probably *want* to have a separate timeline for
when planned units gets updated from when you call add_relation_unit.

**Comment by mmanciop** [comment] 2021-10-20 12:45
I was trying the mocking of `ops/testing.py::_TestingModelBackend.planned_units`, and I am wondering if there is a way in the charm to listen to changes to it. Does a, dunno, `config_changed` event fire when the planned units for the charm change?

**Comment by jameinel** [comment] 2021-10-20 13:13
I would probably just add `testing.Harness.set_planned_units(N)` and not
try to abstract through goal-state. Yes it happens to be implemented that
way, but if we can change the response from `get_planned_units()` rather
than having a charm author go via a deprecated interaction. (We may have to
have set_planned_units generate a fake goal-state response, but I would
want that hidden underneath Harness and not exposed to the charmer)

At present juju doesn't generate an event when goal state changes (one of
its many failings), so there isn't an equivalent event for the framework to
generate.
But at the very least having Harness.set_planned_units() would let charmers
test their logic around what the number of units they expect to see, and
how many units show up from add_relation_unit.

**Comment by petevg** [comment] 2021-10-20 13:21
@jameinel thanks for the comment. I probably shouldn't have mentioned goal state at all in my comments, because folks tend to focus on it being deprecated. Planned units is meant to be an abstraction around the parts of goal state that we want to keep.

Regardless, I think that the issue here is not about overriding the hardness. Michele can do that, and get an arbitrary number back from planned units.

The issue is that it's unclear how well that will test production behavior. Where does he put his check for planned units? How can he be sure that the logic will execute when he runs his charm in production?

**Comment by petevg** [comment] 2021-10-20 20:53
Thank you for the discussion here.

I think that I have a better idea of some of the historical intent in the harness code, and I'm more on board with letting folks directly set planned_units, rather than forcing them to add a peer.

I can work on putting together a PR addressing this. Though I think that, as noted above, @mmanciop's use case probably does need to be addressed by adding a peer relation, as the most consistent (and correct, I think) way of a charm getting information about its peers.

**Closed** 2021-12-03 11:08 UTC
Labels: enhancement, harness
