### ISSUE TITLE
Introspection for events

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#416] opened 2020-09-24 08:57 UTC
Names of events that can be bound to hooks are specified be members of the `on` event descriptor, which are not the same as the names of the event classes. For this reason it may be a good idea to have a `__str__` or `__repr__` representation of the event descriptor that lists the names of currently available events.

**Comment by balbirthomas** [comment] 2020-09-25 12:23
This is one possible suggestion for a representation that can link the event class to the instance, thereby guiding the programmer where to look for event documentation. For example if the string representation of the event descriptor is a mapping like

    { 'config_changed': 'ConfigChagnedEvent'}

then he/she knows that the docstring for `ConfigChagnedEvent` will provide more information about `config_chagned`

**Comment by chipaca** [comment] 2020-09-28 17:06
I think this is a dupe of #250

**Closed** 2020-10-29 20:08 UTC
