### ISSUE TITLE
Pods are restarted because of a WebSocketBadStatusException in Pebble

### ISSUE THREAD

**Issue by ben-ballot** [canonical/operator#1097] opened 2024-01-02 11:18 UTC
Some pods are being restarted frequently because of the liveness and readiness probe failing.

Here is a sample of the log message in the pods
```
2024-01-02T08:33:46.490Z [container-agent] 2024-01-02 08:33:46 WARNING juju-log Convert legacy openstack object storage configuration prefix (wp-content/uploads/) to object-prefix (wp-content/uploads/)
2024-01-02T08:33:50.561Z [container-agent] 2024-01-02 08:33:50 ERROR juju-log Uncaught exception while in charm code:
2024-01-02T08:33:50.561Z [container-agent] Traceback (most recent call last):
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
2024-01-02T08:33:50.561Z [container-agent]     h.request(req.get_method(), req.selector, req.data, headers,
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/http/client.py", line 1283, in request
2024-01-02T08:33:50.561Z [container-agent]     self._send_request(method, url, body, headers, encode_chunked)
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
2024-01-02T08:33:50.561Z [container-agent]     self.endheaders(body, encode_chunked=encode_chunked)
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
2024-01-02T08:33:50.561Z [container-agent]     self._send_output(message_body, encode_chunked=encode_chunked)
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
2024-01-02T08:33:50.561Z [container-agent]     self.send(msg)
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/http/client.py", line 976, in send
2024-01-02T08:33:50.561Z [container-agent]     self.connect()
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 272, in connect
2024-01-02T08:33:50.561Z [container-agent]     self.sock.connect(self.socket_path)
2024-01-02T08:33:50.561Z [container-agent] FileNotFoundError: [Errno 2] No such file or directory
2024-01-02T08:33:50.561Z [container-agent]
2024-01-02T08:33:50.561Z [container-agent] During handling of the above exception, another exception occurred:
2024-01-02T08:33:50.561Z [container-agent]
2024-01-02T08:33:50.561Z [container-agent] Traceback (most recent call last):
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1599, in _request_raw
2024-01-02T08:33:50.561Z [container-agent]     response = self.opener.open(request, timeout=self.timeout)
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
2024-01-02T08:33:50.561Z [container-agent]     response = self._open(req, data)
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
2024-01-02T08:33:50.561Z [container-agent]     result = self._call_chain(self.handle_open, protocol, protocol +
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
2024-01-02T08:33:50.561Z [container-agent]     result = func(*args)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 286, in http_open
2024-01-02T08:33:50.561Z [container-agent]     return self.do_open(_UnixSocketConnection, req,  # type:ignore
2024-01-02T08:33:50.561Z [container-agent]   File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
2024-01-02T08:33:50.561Z [container-agent]     raise URLError(err)
2024-01-02T08:33:50.561Z [container-agent] urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>
2024-01-02T08:33:50.561Z [container-agent]
2024-01-02T08:33:50.561Z [container-agent] During handling of the above exception, another exception occurred:
2024-01-02T08:33:50.561Z [container-agent]
2024-01-02T08:33:50.561Z [container-agent] Traceback (most recent call last):
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1445, in <module>
2024-01-02T08:33:50.561Z [container-agent]     main(WordpressCharm)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/main.py", line 441, in main
2024-01-02T08:33:50.561Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
2024-01-02T08:33:50.561Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 344, in emit
2024-01-02T08:33:50.561Z [container-agent]     framework._emit(event)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 841, in _emit
2024-01-02T08:33:50.561Z [container-agent]     self._reemit(event_path)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 930, in _reemit
2024-01-02T08:33:50.561Z [container-agent]     custom_handler(event)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1415, in _reconciliation
2024-01-02T08:33:50.561Z [container-agent]     self._plugin_reconciliation()
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1379, in _plugin_reconciliation
2024-01-02T08:33:50.561Z [container-agent]     self._plugin_swift_reconciliation()
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1336, in _plugin_swift_reconciliation
2024-01-02T08:33:50.561Z [container-agent]     self._config_swift_plugin(swift_config)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1324, in _config_swift_plugin
2024-01-02T08:33:50.561Z [container-agent]     result = self._activate_plugin(
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1058, in _activate_plugin
2024-01-02T08:33:50.561Z [container-agent]     activate_result = self._perform_plugin_activate_or_deactivate(plugin, "activate")
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1016, in _perform_plugin_activate_or_deactivate
2024-01-02T08:33:50.561Z [container-agent]     current_plugins = self._wp_addon_list("plugin")
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 830, in _wp_addon_list
2024-01-02T08:33:50.561Z [container-agent]     process = self._run_wp_cli(["wp", addon_type, "list", "--format=json"], timeout=600)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 518, in _run_wp_cli
2024-01-02T08:33:50.561Z [container-agent]     result = self._run_cli(
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 482, in _run_cli
2024-01-02T08:33:50.561Z [container-agent]     stdout, stderr = process.wait_output()
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1354, in wait_output
2024-01-02T08:33:50.561Z [container-agent]     exit_code: int = self._wait()
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1294, in _wait
2024-01-02T08:33:50.561Z [container-agent]     change = self._client.wait_change(self._change_id, timeout=timeout)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1794, in wait_change
2024-01-02T08:33:50.561Z [container-agent]     return self._wait_change_using_wait(change_id, timeout)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1815, in _wait_change_using_wait
2024-01-02T08:33:50.561Z [container-agent]     return self._wait_change(change_id, this_timeout)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1829, in _wait_change
2024-01-02T08:33:50.561Z [container-agent]     resp = self._request('GET', f'/v1/changes/{change_id}/wait', query)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1564, in _request
2024-01-02T08:33:50.561Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2024-01-02T08:33:50.561Z [container-agent]   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1612, in _request_raw
2024-01-02T08:33:50.561Z [container-agent]     raise ConnectionError(e.reason)
2024-01-02T08:33:50.561Z [container-agent] ops.pebble.ConnectionError: [Errno 2] No such file or directory
2024-01-02T08:38:49.950Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready Exception in thread Thread-11 (copyfileobj):
2024-01-02T08:38:49.950Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready Traceback (most recent call last):
2024-01-02T08:38:49.951Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-01-02T08:38:49.953Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready Exception in thread Thread-10 (copyfileobj):
2024-01-02T08:38:49.953Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready Traceback (most recent call last):
2024-01-02T08:38:49.953Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-01-02T08:38:49.953Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     self.run()
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/usr/lib/python3.10/threading.py", line 953, in run
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     self._target(*self._args, **self._kwargs)
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     self.run()
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/usr/lib/python3.10/threading.py", line 953, in run
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     buf = fsrc_read(length)
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1509, in read1
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     self._target(*self._args, **self._kwargs)
2024-01-02T08:38:49.954Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
2024-01-02T08:38:49.955Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     buf = fsrc_read(length)
2024-01-02T08:38:49.955Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1509, in read1
2024-01-02T08:38:49.957Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     return self.read(n)
2024-01-02T08:38:49.957Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1481, in read
2024-01-02T08:38:49.957Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     chunk = self.ws.recv()
2024-01-02T08:38:49.957Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 364, in recv
2024-01-02T08:38:49.957Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     return self.read(n)
2024-01-02T08:38:49.957Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1481, in read
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     chunk = self.ws.recv()
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 364, in recv
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     opcode, data = self.recv_data()
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 387, in recv_data
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     opcode, frame = self.recv_data_frame(control_frame)
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 408, in recv_data_frame
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     frame = self.recv_frame()
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 447, in recv_frame
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     return self.frame_buffer.recv_frame()
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_abnf.py", line 340, in recv_frame
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     self.recv_header()
2024-01-02T08:38:49.958Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_abnf.py", line 296, in recv_header
2024-01-02T08:38:49.959Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     header = self.recv_strict(2)
2024-01-02T08:38:49.960Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_abnf.py", line 375, in recv_strict
2024-01-02T08:38:49.960Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     bytes_ = self.recv(min(16384, shortage))
2024-01-02T08:38:49.960Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 531, in _recv
2024-01-02T08:38:49.960Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     return recv(self.sock, bufsize)
2024-01-02T08:38:49.960Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_socket.py", line 124, in recv
2024-01-02T08:38:49.960Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     raise WebSocketConnectionClosedException(
2024-01-02T08:38:49.961Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     opcode, data = self.recv_data()
2024-01-02T08:38:49.961Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
2024-01-02T08:38:49.961Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 387, in recv_data
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     opcode, frame = self.recv_data_frame(control_frame)
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 408, in recv_data_frame
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     frame = self.recv_frame()
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 447, in recv_frame
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     return self.frame_buffer.recv_frame()
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_abnf.py", line 340, in recv_frame
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     self.recv_header()
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_abnf.py", line 296, in recv_header
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     header = self.recv_strict(2)
2024-01-02T08:38:49.962Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_abnf.py", line 375, in recv_strict
2024-01-02T08:38:49.963Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     bytes_ = self.recv(min(16384, shortage))
2024-01-02T08:38:49.963Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_core.py", line 531, in _recv
2024-01-02T08:38:49.963Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     return recv(self.sock, bufsize)
2024-01-02T08:38:49.963Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready   File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/websocket/_socket.py", line 124, in recv
2024-01-02T08:38:49.963Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready     raise WebSocketConnectionClosedException(
2024-01-02T08:38:49.963Z [container-agent] 2024-01-02 08:38:49 WARNING wordpress-pebble-ready websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
2024-01-02T08:38:50.297Z [container-agent] 2024-01-02 08:38:50 ERROR juju.worker.uniter.operation runhook.go:153 hook "wordpress-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
2024-01-02T08:38:50.304Z [container-agent] 2024-01-02 08:38:50 ERROR juju.worker.uniter pebblepoller.go:101 pebble poll failed for container "wordpress": failed to send pebble-ready event: hook failed
```

While not being exactly the same, this seems to have some similarities with https://github.com/canonical/operator/issues/826

**Comment by benhoyt** [comment] 2024-01-03 02:33
I don't think this is related to #826, as that's an issue with exec, which doesn't look like it's involved here.

I think we're going to need more information / diagnostics. As far as I can tell, the logs just show that the pod is not able to be contacted, presumably because it's been restarted? But why the liveness/readiness checks are failing we can't tell without more info.

What is your Pebble layer config, particularly the check configuration? Do you know why the liveness/readiness checks are failing, or can we debug that further?

**Comment by benhoyt** [comment] 2024-03-08 00:43
@ben-ballot This sounds awfully like https://bugs.launchpad.net/juju/+bug/2052517, in which the health check endpoint was taking >1s on occasion, causing the Kubernetes liveness probe to time out and recycle the container. If you're able to check with the fixed version of Pebble, that would be great (I can tell you which versions of Juju have the fix -- just ask and I'll look those up). So I'm closing this preemptively, but feel to re-open if you can reproduce with the fixed Pebble.

**Closed by benhoyt** 2024-03-08 00:43 UTC
Labels: blocked
