### ISSUE TITLE
Operator framework should support pod readiness event

### ISSUE THREAD

**Issue by tcuthbert** [canonical/operator#214] opened 2020-04-06 01:07 UTC
I have a scenario where I need my charm to be notified once the workload pod is alive and ready. It would be useful for the operator framework to be signaled an event once the kubernetes pod readiness probe is green so that we can handle that and perform out application initialisation procedures.

**Comment by jameinel** [comment] 2020-04-23 07:55
Duplicate of #166

**Closed** 2020-05-01 16:19 UTC
