### ISSUE TITLE
Helper functions to write charms

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/operator#536] opened 2021-05-19 18:44 UTC
The more charms we write, the more helper functions/methods we end up writing.

These are just a few examples:

- [Function to generate passwords](https://github.com/canonical/cassandra-operator/blob/master/lib/charms/cassandra/v1/cql.py#L138) in the cassandra lib charm.
- [Method to generate passwords](https://github.com/canonical/mysql-operator/pull/44/files/cb04f699129739e0f9bf44aa54237b78ca55828e#diff-12d09ebb9479d37d2988406fc8c9f96ceee9a61f1919ab9e2edb7903ad1e0518R181) in the mysql charm.
- Method to [get the unit IP address](https://github.com/canonical/mysql-operator/pull/44/files/cb04f699129739e0f9bf44aa54237b78ca55828e#diff-b9ed39bbc9c0387bd3e07da31d13373745534a1cd723d3e292c73496b12e307cR184)

This code will end up being replicated across many charms and potentially in insecure ways.

Should something like `ops.utils` be the right place for all this kind of helper functions?

**Comment by dstathis** [comment] 2021-05-19 18:54
I think this would be ideal. A place to put small functions that are going to be used over and over again.

**Comment by sed-i** [comment] 2021-05-19 20:12
I'd be happy to contribute:
### ops
- `unit_id(self) -> int`
- `is_service_running(self, service_name: str) -> bool`
- `restart_service(self, service_name: str)`
### utils
- `leader_only(func)` (decorator)
- `fetch_url(url: str) -> Union[str, None]`

**Comment by benhoyt** [comment] 2021-05-20 01:01
@Abuelodelanada  Thanks for the suggestions. I'm not a big fan of adding generic tools like "generate password". I don't think we should be adding things that aren't specific to charming to the operator framework. It's fine to use your favourite password generation library from PyPI, or just write the one-liner generation function that satisfies your needs like you've done.

As far as fetching the unit's IP address, doesn't this depend on the network configuration and relations involved? Again, you can use the tools like `get_binding()` to do what your specific charm needs (like you've done). But I'd be happy to hear a more specific proposal for what you have in mind here, so we can discuss specifics.

@sed-i Can you provide a more specific explanation for what each of those functions is intended to do, perhaps with pseudo-code and a context example? Then we could discuss them on their specific merits. The only one I think we'd definitely not add is `fetch_url` -- this is a minefield, and there are so many ways of fetching URL, so many options etc, that that's definitely best left for a library like `requests`.

**Comment by benhoyt** [comment] 2021-05-20 01:02
That said, even though I don't think a lot of these functions will end up in `ops` itself, there's nothing stopping you (or us) from making a separate `opshelpers` or similar library with a bunch of helper functions. It wouldn't have to be so carefully vetted as `ops` core.

**Comment by sed-i** [comment] 2021-05-20 07:10
#### `unit_id(self) -> int`
This is complementary to `self.unit.name`. Currently I only use it for logging and it seems that by design, charm code should not have any knowledge about the particular unit id code is executing on. If that is the case then this can be dropped.

#### `is_service_running`
This is a wrapper around `is_running()` (which is used by `restart_service` below).
In my utility function the container name is hard-coded though.
The objects we use the most is services, not containers, yet with the current API we have to go through container.
```python
    def is_service_running(self, service_name: str) -> bool:
        # TODO avoid hard-coding string literals
        container = self.unit.get_container("alertmanager")
        return container.get_service(service_name).is_running()
```

#### `restart_service(self, service_name: str)`
This is used when a config is changed, a layer is changed, as well as in `update_status` to restart the process if the server is not responsive.
```python
    def restart_service(self, service_name: str):
        # TODO avoid hard-coding string literals
        container = self.unit.get_container("alertmanager")

        try:
            # if the service does not exist, ModelError will be raised
            if self.is_service_running(service_name):
                container.stop(service_name)
            container.start(service_name)
        except ops.model.ModelError:
            logger.warning("Service does not (yet?) exist; restart aborted")
        except Exception as e:
            logger.warning("failed to (re)start service: %s", str(e))
            raise
```

#### `leader_only(func)` (decorator)
Instead of the `if not self.unit.is_leader(): return` preamble.

#### `fetch_url(url: str) -> Union[str, None]`
Maybe "fetch" is a bad name. This is a wrapper for checking if an HTTP API server is responsive. A simple one-liner that guarantees returning either a success (str) or failure (None).
But this is definitely a util that has nothing to do with ops.

**Comment by Abuelodelanada** [comment] 2021-05-21 14:25
Hello @benhoyt 

You are right, may be the password examples were not the best ones. The underlying idea is to have a place for common functions that we use every day when charming.

**Comment by rbarry82** [comment] 2021-07-15 18:10
Tracking IP address in #556.

For the rest, passwords were already discussed. Restarting the service is being implemented separately (and explicitly) in both Pebble and OF.

`@defer_on` is a bit of an antipattern, `fetch_url` has too many assumptions baked in about unauthenticated connections/protocol type/etc, `unit_id` is, as you mentioned, probably only useful for logging and is otherwise much less descriptive than the existing `unit.name` property (from which `unit.id` can be trivially derived for those cases where someone developing a charm needs to know it directly), and `leader_only` has very limited use cases.

Closing this and tracking the IP address in #556

**Closed by rbarry82** 2021-07-15 18:10 UTC
Labels: enhancement
