### ISSUE TITLE
Setting the same secret twice generates a new secret ID

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/operator#1055] opened 2023-10-27 07:54 UTC
### Description

Upon updating a secret with the same value, Juju generates a new secret. This impacts dev experience by requiring charm devs to check if a secret has changed before updating to prevent emitting the same event several times by:
- Storing the secret ID
- Creating a peer relation to store the Id retrieved in step 1 if it doesn't exist
- Comparing the contents of the secret with the new value

This behaviour is also inconsistent with how the relation databags work.

IMO, this operation should be idempotent.

### Urgency

Casually reporting

### Python-libjuju version

3.1.6

### Juju version

3.1.6-genericlinux-amd64

### Reproduce / Test

Run twice the following code
```python

secret = self.app.add_secret({"password": "content"})
logger.error(secret.id)
```

**Comment by benhoyt** [comment] 2023-10-30 09:11
Hi @arturo-seijas, this is by design. `add_secret` always creates a new secret (with a new secret ID). You have to use [`Secret.set_content`](https://ops.readthedocs.io/en/latest/#ops.Secret.set_content) to update an existing secret's content. That will still create a new *revision* of the secret (but not a new secret ID). Will that be an issue for you?

**Comment by arturo-seijas** [comment] 2023-10-30 09:39
> Hi @arturo-seijas, this is by design. `add_secret` always creates a new secret (with a new secret ID). You have to use [`Secret.set_content`](https://ops.readthedocs.io/en/latest/#ops.Secret.set_content) to update an existing secret's content. That will still create a new _revision_ of the secret (but not a new secret ID). Will that be an issue for you?

It isn't a functional limitation, but I still see some impact in dev experience. The developer (me) will still have to check the config to prevent multiple secrets or revisions being created. Considering the charm is stateless, this doesn't seem ideal.
In the scenario I'm working on, I'm storing a charm configuration as a secret to share it through an integration. This means that, on every config changed, I would either be creating a new secret or secret revision, unless I check for the secret existence and it's content. IMO this will be a very common scenario, and it seems logical to me that ops provides this out of the box.

**Comment by benhoyt** [comment] 2023-10-31 07:34
I think we should consider this an optimization. Feel free to open a bug on the Juju side for the `secret-set` hook tool to only create a new revision if the content (or metadata) actually changes. That should be transparent to the charm.

That said, can you expand on what you mean by "storing a charm configuration as a secret"? Secrets should only be used for sensitive data like passwords and private keys, not general charm configuration.

**Comment by arturo-seijas** [comment] 2023-10-31 08:36
Will do. I might not have been clear but I'm yes, talking about a sensitive value.

**Comment by benhoyt** [comment] 2023-10-31 08:41
Closing as not planned in light of the above. @arturo-seijas Please add a comment here that links to the Juju bug when you've opened that.

**Closed by benhoyt** 2023-10-31 08:41 UTC

**Comment by arturo-seijas** [comment] 2023-10-31 10:37
It turns out `Secret.set_content` is idempotent, so the main issue is having to track the existence of the secret from a stateless application
