### ISSUE TITLE
Implement a method to expose the version (application-version-set)

### ISSUE THREAD

**Issue by woutervb** [canonical/operator#183] opened 2020-03-13 06:54 UTC
Currently it is not possible to set the version string of the code that the charm is running.

I think it's a matter of adding it to the ModelBackend class in model.py, but there might be a reason it's not implemented yet, so I am willing to implement, unless there are objections.

**Comment by mthaddon** [comment] 2020-03-13 10:31
I think this is a duplicate of https://github.com/canonical/operator/issues/174 ?

**Comment by chipaca** [comment] 2020-03-13 10:38
yep

**Closed by chipaca** 2020-03-13 10:38 UTC
