### ISSUE TITLE
New configs added to a charm not available

### ISSUE THREAD

**Issue by davigar15** [canonical/operator#358] opened 2020-07-09 10:38 UTC
Hello,

I deployed a charm, add a new variable in config.yaml, upgrade the charm, and I get this error:

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pla-6/charm/hooks/upgrade-charm", line 176, in <module>
    main(PLACharm)
  File "lib/ops/main.py", line 344, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "lib/ops/main.py", line 120, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "lib/ops/framework.py", line 212, in emit
    framework._emit(event)
  File "lib/ops/framework.py", line 624, in _emit
    self._reemit(event_path)
  File "lib/ops/framework.py", line 667, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pla-6/charm/hooks/upgrade-charm", line 144, in on_upgrade_charm
    self.on_start(event)
  File "/var/lib/juju/agents/unit-pla-6/charm/hooks/upgrade-charm", line 138, in on_start
    self._apply_spec()
  File "/var/lib/juju/agents/unit-pla-6/charm/hooks/upgrade-charm", line 82, in _apply_spec
    new_spec = self.make_pod_spec()
  File "/var/lib/juju/agents/unit-pla-6/charm/hooks/upgrade-charm", line 111, in make_pod_spec
    "OSMPLA_GLOBAL_REQUEST_TIMEOUT": config["global_request_timeout"],
  File "lib/ops/model.py", line 342, in __getitem__
    return self._data[key]
KeyError: 'global_request_timeout'
```

I set a default value.

**Comment by facundobatista** [comment] 2020-07-10 11:31
Hello! Is the charm code public? Can we take a look at it? Thanks!

**Comment by jameinel** [comment] 2020-07-10 18:46
This sounds more like a Juju issue than a Operator Framework issue.
I know that juju does trigger a config-changed after upgrade-charm, but I
thought the new config *was* available during upgrade-charm (because the
new code may need the new config).

I just confirmed this for IAAS charms, I don't know if there is a problem
for K8s charms:
```
$ juju debug-hooks
```

in one terminal

```
diff --git a/config.yaml b/config.yaml
index a985d46..14f2c78 100644
--- a/config.yaml
+++ b/config.yaml
@@ -1 +1,4 @@
-options: {}
+options:
+    foo:
+        type: string
+        default: "default of foo"

$ juju upgrade-charm uo --path .
```

And then in the debug-hooks session:
```
# config-get
foo: default of foo
```

Being able to look at the charm would be useful, but I would expect the
above to work. (Operator Framework doesn't do any caching of config content
that I am aware of.)

**Comment by chipaca** [comment] 2020-07-15 12:05
@davigar15 any news?

**Comment by chipaca** [comment] 2020-08-05 12:39
Closing this, suspecting there was something else going on that caused this and not a bug on our side. If you can reproduce this, or think it's an actual operator bug, please do reach out (or just reopen) with more info. Thanks!

**Closed by chipaca** 2020-08-05 12:39 UTC
