### ISSUE TITLE
Link docstrings to package level

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#441] opened 2020-10-30 14:04 UTC
## Use Case

A busy programmer does not want to divert his attention from their IDE and would like to get documentation for the operator framework in said IDE. For example the programmer does `import ops` and would now like to get contextual help on `ops`. 

## Issue

At present trying to access the documentation for the `ops` module produces an almost blank screen.

**Comment by facundobatista** [comment] 2020-10-30 14:08
Please specify the details on how you're accessing the docs, thanks!

**Comment by chipaca** [comment] 2020-11-04 13:41
The issue seems to be that `elpy` only shows the module- or package-docstring, nothing about the things that module or package contains. `pydoc ops` is serviceable, if minimal, whereas C-c C-d on `ops` in a charm's buffer just shows `The Operator Framework.`.

We should improve the toplevel docstrings, but elpy does not (apparently by design) link to the things contained inside. I'm not sure we have a say in that.

The only way you see more than the toplevel docstring is if your module has no docstring at all, in which case it shows what pydoc generates.

**Comment by jnsgruk** [comment] 2021-09-28 16:15
Fixed in #511 :)

**Closed by jnsgruk** 2021-09-28 16:15 UTC
