### ISSUE TITLE
pebble.exec should expose the called process' exit code

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#877] opened 2023-01-09 12:56 UTC
at the moment, `pebble.exec().wait()` returns None, while `pebble.exec().get_output()` returns stderr/stdout, but there seems to be no way to obtain the exit code of the command.

**Comment by dstathis** [comment] 2023-01-09 13:05
+1 this would be very useful

**Comment by benhoyt** [comment] 2023-01-10 02:33
After looking at this again, I realize the initial design was that `ExecProcess.wait()` shouldn't return anything, but will raise a `pebble.ExecError` exception if the exit code is non-zero --this is similar to `subprocess.run(args, check=True)` raising `CalledProcessError` when the exit code is non-zero. And `ExecError` has an `exit_code` attribute for getting the exit code.

So to get the exit code of an exec, you'd use something like this:

```python
def my_method(self):
    container = self.model.containers['mycontainer']
    try:
        process = container.exec(['/bin/sh', '-c', 'exit 42'])
        process.wait()
    except pebble.ExecError as e:
        logger.warning(f'exit code {e.exit_code}')  # should log "exit code 42"
```

Similar with `ExecProcess.wait_output()`: that returns the `(stdout, stderr)` tuple on success, or raises `ExecError` on non-zero exit code.

We *could* add an `exit_code` attribute to `ExecProcess` as well, but I'd rather not for two reasons:

* It's not valid till `wait()` or `wait_output()` finish anyway, meaning you have this intermediate `None` state (not ready yet) for the `ExecProcess.exit_code` attribute.
* You'd still have to catch the exception raised by wait/wait_output, so it wouldn't save you any typing in any case.

**Comment by PietroPasotti** [comment] 2023-01-10 08:06
Well if we're going for least surprise, I'd argue that the most popular API for doing this kind of things disagrees with this pattern. If we look at subprocess:

- calledprocess.exit_code is None until you call .wait(), which is what I was going for
- calledprocess.wait() never raises. instead you're supposed to manually fetch exit_code and check for nonzero
- there's a separate subprocess.check_output that raises on nonzero.

I see now how you're supposed to fetch the exit code, but it feels different from what I'd expect given `subprocess`, and I'd rather not have to try/except around every pebble exec call.

**Comment by jnsgruk** [comment] 2023-01-10 09:29
It looks like `subprocess` uses `returncode` - I think the analogous call is described [here](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode)

I'm not against adding a similar addition to `exec`, but we do need to determine the raise/exception behaviour. It looks like `Popen.wait()` is only [supposed to raise](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait) if the call times out - we'd just need to be careful not to introduce a breaking change to our own API.

**Comment by benhoyt** [comment] 2023-01-11 01:33
For better or worse, this ship has already sailed, as we have already determined the behaviour of raising an exception by default as well as chosen the `exit_code` field name -- these were released in `ops` with the initial version of exec. However, this is by design, and I think for the better -- see rationale below.

**Raising an exception by default**

We (me, and I remember discussions with Gustavo and John at the time) designed exec -- specifically `wait()` and `wait_output()` -- to raise rather than returning the exit code. The thinking was that this is almost always what you want: if the command fails, you almost never want that to silently be ignored. See also [PEP 20 - The Zen of Python](https://peps.python.org/pep-0020/): "Errors should never pass silently."

Python's `subprocess` has the opposite default, but this module is quite old (added in Python 2.4 back in 2004), and so the exception behaviour is likely only for historical reasons. The `subprocess.check_call()` function was [added in Python 2.5](https://bugs.python.org/issue1071764) with the exact rationale of not letting errors pass silently: 

> I consider raising an exception to be much more pythonic than checking a return code (ie "Errors should never pass silently" from Zen of Python). Eg
>
>     # An easy to miss error
>     >>> subprocess.call(["mkdir", "a/b"])
>     mkdir: cannot create directory `a/b': No such file or directory
>     1
>     >>>
>     # user forgot to check non-zero return code
>     # becomes an impossible to miss exception

The `run()` function was added later and has a `check=False` keyword arg (the default is unchecked presumably to be consistent with the existing `subprocess` calls, not because that's the ideal API.

We wanted to correct this in the exec API, so we designed it in the spirit of The Zen of Python -- errors are raised so they don't pass silently. I think this is still true in the context of charms: if you run a command and it fails, you don't want the hook succeeding silently. We do this with hook tool calls too (`subprocess` raises `CalledProcessError`, which we re-raise as `ModelError`).

@PietroPasotti What's your specific use case for avoiding a try/except block and fetching the exit code directly? If you really want that, I'd suggest writing a 5-line helper function in the charm, something like so:

```python
def my_exec(container, command, **kwargs):
    """Exec command and wait(), but return exit code rather than raising ExecError."""
    try:
        container.exec(command, **kwargs).wait()
        return 0
    except pebble.ExecError as e:
        return e.exit_code
```

**The name `exit_code`**

This one is more of a bikeshedding issue. Back when I designed exec, I remember being on the fence about choosing `returncode` vs `return_code` vs `exit_code`. I think it's weird that "old Python" APIs often don't have underscores between words (though many do! it's inconsistent). So I thought of `return_code`, but that's probably the worst of both worlds -- not the same as `subprocess` but not different enough to be obviously different. So ended up choosing `exit_code`, which is what we have now.

Hope that explains the rationale. I'm going to close this now, though feel free to send further comments if you want.

**Closed by benhoyt** 2023-01-11 01:33 UTC
